F: assets/default/Cobblestone.jpg
DT: assets/default/DoorHoriz.png
DB: assets/default/DoorHoriz.png
DL: assets/default/DoorVert.png
DR: assets/default/DoorVert.png
DST: assets/default/DoorSecretHoriz.png
DSB: assets/default/DoorSecretHoriz.png
DSR: assets/default/DoorSecretVert.png
DSL: assets/default/DoorSecretVert.png
DPT: assets/default/DoorHoriz.png
DPB: assets/default/DoorHoriz.png
DPR: assets/default/DoorVert.png
DPL: assets/default/DoorVert.png
W: assets/default/Wall.jpg
